apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-configmap
data:
  config.yml: |-
    server:
      port: 8090
    kafka:
      clusters:
        - name: yaml
          bootstrapServers: kafka-broker.default.svc.cluster.local:9092
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false
# TODO see https://docs.kafka-ui.provectus.io/configuration/helm-charts/quick-start

# kafka-broker.default.svc.cluster.local:9092
# zookeeper-svc.default.svc.cluster.local:2181
# [podname].broker.kafka.svc.cluster.local
# svc/kafka-broker